### ISSUE TITLE
Remove Field Formatter Settings dependency

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/field_html_trim#1]
Remove dependency on Field Formatter Settings now that this [is in core](https://github.com/backdrop/backdrop-issues/issues/1376).

**Comment by laryn** [comment]
Don't forget to update the README: "Field HTML Trim adds settings to text field formatters (via the Field Formatter Settings module)..."

**Comment by ghost** [comment]
Fixed with https://github.com/backdrop-contrib/field_html_trim/commit/8b80decf082ab0ce8917896e9e0ca4e9a051e378 and included in https://github.com/backdrop-contrib/field_html_trim/releases/tag/1.x-1.0.1.
